apiVersion: v1
kind: Config
clusters:
- name: gke-cluster
  cluster:
    certificate-authority-data: <your-certificate-authority-data>
    server: <your-cluster-api-endpoint>
users:
- name: gke-user
  user:
    username: <your-username>
    password: <your-password>
contexts:
- name: gke-context
  context:
    cluster: gke-cluster
    user: gke-user
current-context: gke-context
