apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
        - name: game
          image: <your-docker-image-name>
          ports:
            - containerPort: 80
